### ISSUE TITLE
Assigning inf prior to x**3

### ISSUE THREAD

**Issue by tomasdsousa** [DeaglanBartlett/katz#2]
When evaluating the logprior for x0**3, with "cube" in the basis functions, the following error occurs:

"/katz/katz/prior.py:56:  RuntimeWarning: divide by zero encountered in log
  p = np.sum(np.log(pleft)) + np.sum(np.log(pright))".
This happens for the training set that I am using, but not for the Feynman one.
[inflation_models_encyclopedia_M.csv](https://github.com/DeaglanBartlett/katz/files/12411338/inflation_models_encyclopedia_M.csv)

```
from katz.prior import KatzPrior
n = 2
basis_functions = [["a", "x"],
    ["cube", "square","cosh","sqrt", "exp", "log", "sin", "cos", "arcsin", "tanh", "atan2"],
    ["+", "-", "*", "/", "pow"]]

#kp = KatzPrior(n, basis_functions, 'katz/data/FeynmanEquations.csv', 'katz/data/NewFeynman.csv')
kp = KatzPrior(n, basis_functions, 'katz/data/inflation_models_encyclopedia_M.csv', 'katz/data/out_inflation.csv', input_delimiter=';')

priors=[]
for eq in ['x0**3', 'x0**2','sin(sin(x0+x1))', 'sin(x0) + sin(x1)']:
  p = kp.logprior(eq)
  priors.append(p)
  print(eq, p)
```

**Comment by DeaglanBartlett** [comment]
This error was raised because the backoff model couldn't find the "cube" operator anywhere in your training data, despite there being two instances of cube within the csv file you gave. The reason for this is that sympy factorised the expressions in that file such that the cube operator was removed. This is clearly unwanted behaviour, since we want the expressions to match those in the file.

To circumvent this, I have added the kwarg `kernS_only` in `esr.generation.generator.string_to_node`
https://github.com/DeaglanBartlett/ESR/blob/1d72504ce8f918319693b658e6b346e0d1b03484/esr/generation/generator.py#L486-L500
such that setting this value to True will only run the `kernS=True` simplifications in ESR, which should avoid this. In the latest commit 28b19d83d82b218495957e377651b1ef91ce23ff we only use `kernS_only=True` when using `esr`:

https://github.com/DeaglanBartlett/katz/blob/28b19d83d82b218495957e377651b1ef91ce23ff/katz/process_equations.py#L206
and
https://github.com/DeaglanBartlett/katz/blob/28b19d83d82b218495957e377651b1ef91ce23ff/katz/process_equations.py#L218

Now running your example gives
```
x0**3 -6.006702636533885
x0**2 -3.7521558496752476
sin(sin(x0+x1)) -25.670007335834654
sin(x0) + sin(x1) -22.977996076306063
```
and I have verified that `katz` indeed finds two instances of "cube".
