### ISSUE TITLE
Trig function being simplified to other trig function not on the basis set

### ISSUE THREAD

**Issue by tomasdsousa** [DeaglanBartlett/katz#7]
Having sin(pi/2-x) on one of the functions in the training set and running Katz priors with sin(x) - but not cos(x) - on the basis set, an error (KeyError: 'cos')  is raised in line 1553 of ESR/generation/generator.py. It seems sin(pi/2-x) is simplified to cos(x), but it was written like that so we didn't need to include cos(x) in the basis set as well, for compatibility with an ESR basis set.

**Comment by DeaglanBartlett** [comment]
In ESR commit b9e615f74868004e3ec75f278fd5bb75056aada7, I have introduced the function `check_operators` (https://github.com/DeaglanBartlett/ESR/blob/b9e615f74868004e3ec75f278fd5bb75056aada7/esr/generation/generator.py#L451C36-L460) which now checks whether the operators used in a tree are within the basis set. When calling `esr.generation.generator.string_to_node()` with `check_ops=True`, it will prioritise functions whose entire tree contains operators within the basis set.

To do this, I also changed the kwarg `kernS_only` in `esr.generation.generator.string_to_node()` discussed in #2 to `allow_eval` (which should be False when `kernS_only` was True) since one of the cases considered in this function was useful for our purposes but wouldn't be accessed with `kernS_only=True`.

@tomasdsousa Please can you pull both the ESR code and this branch of katz and check whether your problem has been fixed as I don't have an example to check on?

**Comment by tomasdsousa** [comment]
Thanks @DeaglanBartlett, it seems I get the same error as before when running run_esr_prior.py

`COMPLEXITY: 4

N-GRAM: 8
Total number of functions:  1152
Number of test points per proc:  1152
Traceback (most recent call last):
  File "/mnt/zfsusers/tomas/destionationDirectory/ESR/esr/generation/generator.py", line 1607, in labels_to_shape
    s[i] = basis_dict[t]
KeyError: 'cos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/zfsusers/tomas/destionationDirectory/run_esr_prior.py", line 59, in <module>
    main()
  File "/mnt/zfsusers/tomas/destionationDirectory/run_esr_prior.py", line 53, in main
    katz.esr_prior.compute_logprior(comp, n, basis_functions, dirname, in_eqfile, out_eqfile, overwrite=True, input_delimiter=input_delimiter, use_tree=use_tree)
  File "/mnt/zfsusers/tomas/destionationDirectory/katz/katz/esr_prior.py", line 208, in compute_logprior
    kp = KatzPrior(n, basis_functions, in_eqfile, out_eqfile, input_delimiter=input_delimiter)
  File "/mnt/zfsusers/tomas/destionationDirectory/katz/katz/prior.py", line 31, in __init__
    t = self.coder.process_all_equations(n+1, [eq], self.maxvar)
  File "/mnt/zfsusers/tomas/destionationDirectory/katz/katz/process_equations.py", line 261, in process_all_equations
    ntuples += self.equation2ntuples(n, eq, locs)
  File "/mnt/zfsusers/tomas/destionationDirectory/katz/katz/process_equations.py", line 235, in equation2ntuples
    ntuples = self.labels2ntuples(n, labels)
  File "/mnt/zfsusers/tomas/destionationDirectory/katz/katz/process_equations.py", line 179, in labels2ntuples
    s = generator.labels_to_shape(labels, self.basis_functions)
  File "/mnt/zfsusers/tomas/destionationDirectory/ESR/esr/generation/generator.py", line 1612, in labels_to_shape
    raise ValueError
ValueError

**Comment by DeaglanBartlett** [comment]
Ah right. Please can you send me the code and the corpus you're using so I can test this myself?

**Comment by tomasdsousa** [comment]
The inflation_setA.csv file has cos(x) as sin(a0-x) and it runs well. Inflation_setA_pi.csv has sin(pi/2-x) instead. I’m running the priors on your run_esr_prior.py script, with basis functions:


basis_functions = [["a", "x"],

                 ["abs","sqrt",  "exp", "log", "square","cube","atan2", "sin",  "inv" ],

                 ["+", "-", "*", "/" ]]

I have slightly modified esr_prior.py due to that sqrt_abs/sqrt issue but it’s nothing important for this.

From: Deaglan Bartlett ***@***.***>
Date: Tuesday, 26 September 2023 at 19:08
To: DeaglanBartlett/katz ***@***.***>
Cc: Tomás Sousa ***@***.***>, Mention ***@***.***>
Subject: Re: [DeaglanBartlett/katz] Trig function being simplified to other trig function not on the basis set (Issue #7)

Ah right. Please can you send me the code and the corpus you're using so I can test this myself?

**Comment by DeaglanBartlett** [comment]
Please can you attach Inflation_setA_pi.csv as I don't have that file?

**Comment by tomasdsousa** [comment]
Sorry I thought you received the attachments I sent.

From: Deaglan Bartlett ***@***.***>
Date: Wednesday, 27 September 2023 at 07:14
To: DeaglanBartlett/katz ***@***.***>
Cc: Tomás Sousa ***@***.***>, Mention ***@***.***>
Subject: Re: [DeaglanBartlett/katz] Trig function being simplified to other trig function not on the basis set (Issue #7)

Please can you attach Inflation_setA_pi.csv as I don't have that file?

**Comment by DeaglanBartlett** [comment]
Using [your basis set](https://github.com/DeaglanBartlett/katz/files/12740740/inflation_setA_pi.csv), I realised that constants were not be identified as being in the basis set since the function `esr.generation.generator.check_operators()` was looking for the pattern e.g. `a3` whereas in the basis set constants are only written as `a`. I have now (ESR commit fa6452d1b3789ff7eeb1fea6afa192dd0183a21e) changed this so that it can find these constants. Running on the toy example

```
from katz.prior import KatzPrior
from esr.generation import generator
import sympy

n = 2
basis_functions = [["a", "x"],
                 ["abs","sqrt",  "exp", "log", "square","cube","atan2", "sin",  "inv" ],
                 ["+", "-", "*", "/" ]]
kp = KatzPrior(n, basis_functions, 'inflation_setA_pi.csv', 'new_inflation_setA_pi.csv', input_delimiter=';')

maxvar = kp.maxvar
x = sympy.symbols([f'x{i}' for i in range(maxvar)], real=True)
a = sympy.symbols([f'a{i}' for i in range(maxvar)], real=True)
d1 = {f'x{i}':x[i] for i in range(len(x))}
d2 = {f'a{i}':a[i] for i in range(len(a))}
locs = {**d1, **d2}

eq = 'sin(pi/2-x)'
p = kp.logprior(eq)
expr, nodes, c = generator.string_to_node(eq, kp.coder.basis_functions, locs=locs, evalf=True, allow_eval=False, check_ops=True)
print(expr)
print(nodes.to_list(kp.coder.basis_functions))
print(eq, p)
```

Gives
```
sin(-x + pi/2)
['sin', 'Sub', 'Div', 'pi', '2', 'x']
sin(pi/2-x) -12.971205348700757
```
suggesting this is working as desired.

@tomasdsousa please can you check when running esr_prior.py on your function set
 (after pulling ESR) you get the correct behaviour?
